### PR TITLE
added R skeleton and functions

### PR DESCRIPTION
**Pull request by jasmin131**
added R skeleton and created first three functions with documentation

### CODE REVIEW

**Review by Deanessoh — COMMENTED** [review]
R-package feedback
The description is very clear and gives a good overview of the purpose of the package. You also use the correct license and list required packages under imports. 
Your function file is also very clear. The documentation for each function makes the purpose and mechanisms of the function easily comprehensible. The only thing I would change is that I would provide an example with parameters as input to your function. As it stands, your function examples have no input. Here, an example of how I would update the example of your 'Get Coordinates' function:
#' @examples
#' # Enter a location (City, Country): Amsterdam, Netherlands
#' get_coordinates(Amsterdam, Netherlands)

Lastly, I see that there is a man file for each of your functions, indicating that your documentation was successfully updated within your R-package. 
Overall, I think you did a great job in creating your R-skeleton!

**Comment by andreeaz19** [comment]
The R package looks good so far! The description is clear and appears complete. Your function documentation makes it easy to follow how each function works. However, I am a bit confused by the examples provided: if a person using the Get Coordinates function enters get_coordinates(), will this then prompt them to enter a city and country? Or do they also need to enter the line of code below that asks for a city and country? The same goes for the Get Weather Data function. Otherwise, the code and the documentation seem correct!

**Comment by saministeru** [comment]
Looking very good! The required elements are present. You have the basic structure, documentation for your functions, the right license. The documentation for the functions is complete. As the other reviewers have already mentioned, I was also a bit confused by the examples. It would be great if you show how the functions are applied for 1-2 locations.

**Review by saministeru — COMMENTED** [review]
Already submitted as a comment

**Comment by andreeaz19** [comment]
I noticed that the examples in your documentation are much more clear compared to last week and cover several different ways to enter input into the function! I also like the memes added into the functions in .Rhistory :) One thing I would check is just the way you've formatted your code. Right now, it is all left aligned. However, it might be easier to read if it includes appropriately indented lines. Also, make sure to add shiny to the imports section of the description file! Otherwise, this looks good to me!

**Comment by jasmin131** [comment]
> I noticed that the examples in your documentation are much more clear compared to last week and cover several different ways to enter input into the function! I also like the memes added into the functions in .Rhistory :) One thing I would check is just the way you've formatted your code. Right now, it is all left aligned. However, it might be easier to read if it includes appropriately indented lines. Also, make sure to add shiny to the imports section of the description file! Otherwise, this looks good to me!

@andreeaz19, thank you for your feedback. Unfortunately, there were a lot of complications with GitHub, merging my branches, and updating my package. So (I am sorry to disappoint;)) I have no idea what memes you are talking about haha. Also, my code is indented (at least in my script) so I am very curious to find out what happened to my script and package on github. Anyways, thank you very much for leaving another comment ;)

**Review by saministeru — COMMENTED** [review]
Very complete, also with an example. The code was reviewed accordingly. Good job!

**Pull request merged**
